export const influencers = [
  {
    id: 'jhds732j',
    firstName: 'Elizabeth',
    lastName: 'Stone',
    nickname: '@lipglosslady',
    photo: '/dashboard/influencer1.png',
    location: 'Canada',
    followers: 14556,
    socialLinks: { instagram: 'https://www.instagram.com/tita_lau/' },
    area: [
      { id: 3, value: 'food and cooking' },
      { id: 25, value: 'cosmetics and skincare' },
    ],
  },
  {
    id: 'jdla732j',
    firstName: 'Jennifer',
    lastName: 'Air',
    nickname: '@orangeamir',
    photo: '/dashboard/influencer2.png',
    location: 'Estonia',
    followers: 1230490,
    socialLinks: { tiktok: 'https://www.tiktok.com/@le_sserafim' },
    area: [{ id: 1, value: 'fashon' }],
  },
  {
    id: 'jd493kj',
    firstName: 'Cortney',
    lastName: 'Fothblake',
    nickname: '@lovelylily',
    photo: '/dashboard/influencer3.png',
    location: 'Finland',
    followers: 2013,
    socialLinks: { youtube: 'https://www.youtube.com/@WawaSensei' },
    area: [{ id: 6, value: 'health' }],
  },
  {
    id: 'jd49oei8',
    firstName: 'Veronica',
    lastName: 'Riverbridge',
    nickname: '@lavenderdaydream',
    photo: '/dashboard/influencer4.png',
    location: 'Ireland',
    followers: 1590,
    socialLinks: { telegram: 'https://web.telegram.org/k/#@fedevelopment' },
    area: [
      { id: 10, value: 'maternity and parenthood' },
      { id: 18, value: 'children' },
    ],
  },
  {
    id: 'oie4oei8',
    firstName: 'Linda',
    lastName: 'White',
    nickname: '@ldsofgh',
    photo: '/dashboard/influencer5.png',
    location: 'Italy',
    followers: 494752,
    socialLinks: { tiktok: 'https://www.tiktok.com/@le_sserafim' },
    area: [{ id: 21, value: 'music' }],
  },
  {
    id: 'oie4848c',
    firstName: 'Mary',
    lastName: 'Hopetown',
    nickname: '@uvjdk',
    photo: '/dashboard/influencer6.png',
    location: 'Poland',
    followers: 9395,
    socialLinks: { instagram: 'https://www.instagram.com/tita_lau/' },
    area: [{ id: 2, value: 'travel' }],
  },
  {
    id: '84j848c',
    firstName: 'Demi',
    lastName: 'Brown',
    nickname: '@aldjj',
    photo: '/dashboard/influencer7.png',
    location: 'Ukraine',
    followers: 373402,
    socialLinks: { telegram: 'https://web.telegram.org/k/#@fedevelopment' },
    area: [{ id: 3, value: 'food and cooking' }],
  },
  {
    id: '84je7cd8',
    firstName: 'Barbara',
    lastName: 'Bitterneet',
    nickname: '@ldjdhdbsslcn',
    photo: '/dashboard/influencer8.png',
    location: 'Germany',
    followers: 564738,
    socialLinks: { youtube: 'https://www.youtube.com/@WawaSensei' },
    area: [{ id: 7, value: 'photography' }],
  },
];
