export const projects = [
  {
    id: '163dh82k9',
    project: 'The best KFC project',
    customer: 'KFC',
    status: 'active',
    linkForSubscribers: 'https://github.com/CollabWave/CollabWave',
    promoCode: 'fast rabbit',
    tasksToDo: 5,
    tasks: [
      { id: 374, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
      { id: 375, description: 'Fast Refresh had to perform a full reload', status: 'unsubmited' },
      { id: 376, description: 'Fast Refresh had to perform a full reload', status: 'unsubmited' },
      { id: 377, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
      { id: 378, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
    ],
    tasksDone: 3,
    payment: '100$',
  },
  {
    id: '393dlh89dk',
    project: 'Save the world',
    customer: 'World',
    status: 'pending',
    linkForSubscribers: 'Hello subscribers!',
    promoCode: '',
    tasksToDo: 3,
    tasksDone: 0,
    tasks: [
      { id: 474, description: 'Fast Refresh had to perform a full reload', status: 'unsubmited' },
      { id: 475, description: 'Fast Refresh had to perform a full reload', status: 'unsubmited' },
      { id: 476, description: 'Fast Refresh had to perform a full reload', status: 'unsubmited' },
    ],
    payment: '0$',
  },
  {
    id: '023je83m92',
    project: 'Successful mwp',
    customer: 'LDC',
    status: 'closed',
    linkForSubscribers: 'Shit!',
    promoCode: 'oh no!',
    tasksToDo: 100000,
    tasks: [
      { id: 575, description: 'Fast Refresh had to perform a full reload', status: 'unsubmited' },
    ],
    tasksDone: 0,
    payment: '0$',
  },
  {
    id: 'j37sj380n',
    project: 'Project to do',
    customer: 'Smb',
    status: 'pending',
    linkForSubscribers: '',
    promoCode: 'promo',
    tasksToDo: 1,
    tasksDone: 0,
    tasks: [
      { id: 776, description: 'Fast Refresh had to perform a full reload', status: 'unsubmited' },
    ],
    payment: '0$',
  },
  {
    id: 'ge83j202kd',
    project: 'Something good',
    customer: 'GOD',
    status: 'active',
    linkForSubscribers: 'Good!',
    promoCode: 'good',
    tasksToDo: 10,
    tasksDone: 6,
    tasks: [
        { id: 3742, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
        { id: 3755, description: 'Fast Refresh had to perform a full reload', status: 'unsubmited' },
        { id: 6376, description: 'Fast Refresh had to perform a full reload', status: 'unsubmited' },
        { id: 3377, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
        { id: 3708, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
        { id: 3793, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
        { id: 3222, description: 'Fast Refresh had to perform a full reload', status: 'unsubmited' },
        { id: 3037, description: 'Fast Refresh had to perform a full reload', status: 'unsubmited' },
        { id: 3932, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
        { id: 38362, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
      ],
    payment: '23$',
  },
  {
    id: 'd7391xja0',
    project: 'Something bad',
    customer: 'DEVIL',
    status: 'closed',
    linkForSubscribers: '',
    promoCode: 'bad',
    tasksToDo: 6,
    tasksDone: 6,
    tasks: [
        { id: 13742, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
        { id: 13377, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
        { id: 13708, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
        { id: 13793, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
        { id: 13932, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
        { id: 138362, description: 'Fast Refresh had to perform a full reload', status: 'submited' },
      ],
    payment: '666$',
  },
];
