export const projects = [
  {
    id: '163dh82k9',
    project: 'The best KFC project',
    customer: 'KFC',
    status: 'active',
    linkForSubscribers: 'https://github.com/CollabWave/CollabWave',
    promoCode: 'fast rabbit',
    tasks: [
      {
        id: 374,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        type: 'reals',
        periodOfExecution: '2023/11/01 - 2023/12/01',
        datePublished: '2023/11/12',
        hashtags: '#tag #hash',
        wordsToUse: 'KFC, delicious, best',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 375,
        description:
          'Mauris pulvinar elementum augue, ac hendrerit lectus sagittis a. Integer tortor dolor, dapibus in urna quis, dictum bibendum orci. Suspendisse potenti. Fusce euismod, metus vulputate eleifend pulvinar, sem dolor ornare mauris, gravida vehicula nisl leo quis ipsum.',
        status: 'not started',
        type: 'reals',
        periodOfExecution: '2023/11/10 - 2023/12/10',
        datePublished: '',
        wordsToUse: 'KFC, delicious, best, chicken',
        link: '',
        screenshotsForVerification: [],
        screenshots: [],
      },
      {
        id: 376,
        description:
          'Proin porta ex nec augue facilisis porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut erat sit amet mi efficitur sagittis. Phasellus id condimentum velit. Sed a arcu purus. Proin quis fringilla arcu. Ut ullamcorper nulla augue, nec tincidunt elit interdum sed. Suspendisse et quam lectus. Sed pharetra venenatis massa id elementum. Maecenas vel massa nisi. Pellentesque et rutrum est. Praesent ut est ligula.',
        status: 'verified',
        type: 'post',
        periodOfExecution: '2023/11/01 - 2023/12/01',
        datePublished: '',
        wordsToUse: '',
        link: '',
        screenshotsForVerification: [],
        screenshots: [],
      },
      {
        id: 377,
        description:
          'Etiam rhoncus porta velit ut porta. Sed egestas blandit tellus ut sollicitudin. Integer finibus neque vitae felis placerat ullamcorper et sed magna. Aliquam et mollis mi, quis euismod ipsum.',
        status: 'submitted',
        periodOfExecution: '2023/11/01 - 2023/12/01',
        type: 'video',
        datePublished: '2023/11/13',
        hashtags: '#tag #tocopy',
        wordsToUse: 'KFC, delicious, best, chicken, sauce',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
          {
            uid: '-2',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 378,
        description:
          'Integer suscipit luctus libero non tempus. Aliquam convallis, orci quis dictum imperdiet, diam orci accumsan nunc, ac congue mi eros eu urna. Suspendisse finibus nisl a mollis consectetur. Sed rhoncus metus vehicula gravida luctus. Mauris elementum pharetra maximus. Vivamus at dui at tellus placerat placerat at convallis orci. Nam facilisis cursus nibh, at tristique diam congue imperdiet.',
        status: 'submitted',
        type: 'reals',
        periodOfExecution: '2023/11/01 - 2023/12/01',
        datePublished: '2023/11/14',
        hashtags: '#tag #hash',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
    ],
    payment: '100$',
  },
  {
    id: '393dlh89dk',
    project: 'Save the world',
    customer: 'World',
    status: 'pending',
    linkForSubscribers: 'Hello subscribers!',
    promoCode: '',
    tasks: [
      {
        id: 474,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'not started',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'post',
        datePublished: '',
        hashtags: '#world #save',
        wordsToUse: 'Hello world!',
        link: '',
        screenshotsForVerification: [],
        screenshots: [],
      },
      {
        id: 475,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'verified',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'video',
        datePublished: '',
        hashtags: '#world #save',
        wordsToUse: 'Hello world!',
        link: '',
        screenshotsForVerification: [],
        screenshots: [],
      },
      {
        id: 476,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'not started',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'reals',
        datePublished: '',
        hashtags: '#world #save',
        wordsToUse: 'Hello world!',
        link: '',
        screenshotsForVerification: [],
        screenshots: [],
      },
    ],
    payment: '0$',
  },
  {
    id: '023je83m92',
    project: 'Successful mwp',
    customer: 'LDC',
    status: 'closed',
    linkForSubscribers: 'Shit!',
    promoCode: 'oh no!',
    tasks: [
      {
        id: 575,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'not started',
        periodOfExecution: '2023/09/01 - 2023/09/16',
        type: 'video',
        datePublished: '',
        hashtags: '#success',
        wordsToUse: '',
        link: '',
        screenshotsForVerification: [],
        screenshots: [],
      },
    ],
    payment: '0$',
  },
  {
    id: 'j37sj380n',
    project: 'Project to do',
    customer: 'Smb',
    status: 'pending',
    linkForSubscribers: '',
    promoCode: 'promo',
    tasks: [
      {
        id: 776,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'verified',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'post',
        datePublished: '',
        hashtags: '#project',
        wordsToUse: 'deadline, project',
        link: '',
        screenshotsForVerification: [],
        screenshots: [],
      },
    ],
    payment: '0$',
  },
  {
    id: 'ge83j202kd',
    project: 'Something good',
    customer: 'GOD',
    status: 'active',
    linkForSubscribers: 'Good!',
    promoCode: 'good',
    tasks: [
      {
        id: 3742,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'reals',
        datePublished: '2023/12/10',
        hashtags: '#god #angel #love',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 3755,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'verified',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'post',
        datePublished: '',
        hashtags: '#god #angel #love',
        wordsToUse: '',
        link: '',
        screenshotsForVerification: [],
        screenshots: [],
      },
      {
        id: 6376,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'not started',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'reals',
        datePublished: '',
        hashtags: '#god #angel #love',
        wordsToUse: '',
        link: '',
        screenshotsForVerification: [],
        screenshots: [],
      },
      {
        id: 3377,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'post',
        datePublished: '2023/12/10',
        hashtags: '#god #angel #love',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 3708,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'reals',
        datePublished: '2023/12/10',
        hashtags: '#god #angel #love',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 3793,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'post',
        datePublished: '2023/12/10',
        hashtags: '#god #angel #love',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 3222,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'verified',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'post',
        datePublished: '',
        hashtags: '#god #angel #love',
        wordsToUse: '',
        link: '',
        screenshotsForVerification: [],
        screenshots: [],
      },
      {
        id: 3037,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'not started',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'post',
        datePublished: '',
        hashtags: '#god #angel #love',
        wordsToUse: '',
        link: '',
        screenshotsForVerification: [],
        screenshots: [],
      },
      {
        id: 3932,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'post',
        datePublished: '2023/12/10',
        hashtags: '#god #angel #love',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 38362,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/12/01 - 2024/01/01',
        type: 'post',
        datePublished: '2023/12/10',
        hashtags: '#god #angel #love',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
    ],
    payment: '23$',
  },
  {
    id: 'd7391xja0',
    project: 'Something bad',
    customer: 'DEVIL',
    status: 'closed',
    linkForSubscribers: '',
    promoCode: 'bad',
    tasks: [
      {
        id: 13742,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/09/01 - 2023/09/16',
        type: 'reals',
        datePublished: '2023/09/10',
        hashtags: '#devil #evil',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 13377,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/09/01 - 2023/09/16',
        type: 'post',
        datePublished: '2023/09/10',
        hashtags: '#devil #evil',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 13708,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/09/01 - 2023/09/16',
        type: 'video',
        datePublished: '2023/09/10',
        hashtags: '#devil #evil',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 13793,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/09/01 - 2023/09/16',
        type: 'reals',
        datePublished: '2023/09/10',
        hashtags: '#devil #evil',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 13932,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/09/01 - 2023/09/16',
        type: 'reals',
        datePublished: '2023/09/10',
        hashtags: '#devil #evil',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
      {
        id: 138362,
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra libero quis massa egestas fermentum. Maecenas hendrerit tempor mollis. Nam laoreet eleifend finibus. Maecenas vitae mattis lectus. Nulla sapien purus, cursus sed dui id, accumsan fermentum lectus. Mauris tempus metus quis pretium laoreet. Sed sed malesuada sem. Etiam in gravida nibh, non tempor nisl.',
        status: 'submitted',
        periodOfExecution: '2023/09/01 - 2023/09/16',
        type: 'post',
        datePublished: '2023/09/10',
        hashtags: '#devil #evil',
        wordsToUse: '',
        link: 'https://github.com/CollabWave/CollabWave',
        screenshotsForVerification: [],
        screenshots: [
          {
            uid: '-1',
            name: 'image.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          },
        ],
      },
    ],
    payment: '666$',
  },
];
