/* export const user = {
  role: 'blogger',
  firstName: 'Mark',
  lastName: 'Cooper',
  nickName: '@MaCoo',
  area: [
    { id: 3, value: 'food and cooking' },
    { id: 25, value: 'cosmetics and skincare' },
  ],
  gender: 'male',
  language: 'english',
  birthDate: '1995/09/01',
  phone: '+372 55596908',
  email: 'mark.cooper@gmail.com',
  countryCode: 'EE',
  country: 'Estonia',
  continent: 'EU',
  city: 'Tallinn',
  address1: 'Peterburi tee 34',
  address2: '',
  zipCode: '11413',
  facebook: 'https://www.facebook.com/profile.php?id=61550583685200',
  instagram: 'https://www.instagram.com/collab_wave/',
  tiktok: '',
  telegram: '',
  youtube: '',
}; */

export const user = {
  role: 'brand',
  brand: 'KFC',
  firstName: 'Harland',
  lastName: 'Sanders',
  position: 'project manager',
  area: { id: 3, value: 'food and cooking' },
  gender: 'male',
  language: 'english',
  birthDate: '1890/09/09',
  phone: '+1 3655596908',
  email: 'harland.sanders@kfc.com',
  countryCode: 'US',
  country: 'USA',
  continent: 'SA',
  city: 'Kentucky',
  address1: '1441 Gardiner Lane Louisville, Kentucky',
  address2: '',
  zipCode: '',
  facebook: 'https://www.facebook.com/KFC/?brand_redir=431070093676539',
  instagram: 'https://www.instagram.com/kfc/',
  tiktok: 'https://www.tiktok.com/channel/kfc',
  telegram: '',
  youtube: 'https://www.youtube.com/KFC',
};
